parameters:
#    test_music.example.class: Test\MusicBundle\Example

services:
#    test_music.example:
#        class: %test_music.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
